# Dockerfile-primary
FROM postgres:latest

ENV POSTGRES_USER=rangga
ENV POSTGRES_PASSWORD=rangga123
ENV POSTGRES_DB=ranggadb

COPY setup-primary.sh /docker-entrypoint-initdb.d/setup-primary.sh
RUN chmod +x /docker-entrypoint-initdb.d/setup-primary.sh
